## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

BNFC       = bnfc
GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

TARGETS = Jezyk/Test Interpreter

.PHONY : all clean distclean

# Default goal.

all : ${TARGETS}

# Rules for building the parser.

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Jezyk/Abs.hs: Jezyk.cf
	${BNFC} -d $<


Jezyk/Test : Jezyk/Abs.hs Jezyk/Lex.hs Jezyk/Par.hs Jezyk/Print.hs Jezyk/Test.hs
	${GHC} ${GHC_OPTS} $@


Interpreter : Jezyk/Abs.hs Jezyk/Lex.hs Jezyk/Par.hs Jezyk/Print.hs Interpreter.hs
	${GHC} ${GHC_OPTS} $@


# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi ${TARGETS} Jezyk/* *~ *.bak
	-rmdir Jezyk


# EOF
