-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Jezyk.

module Jezyk.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Jezyk.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Jezyk.Abs.Ident where
  prt _ (Jezyk.Abs.Ident i) = doc $ showString i
instance Print Jezyk.Abs.Var where
  prt i = \case
    Jezyk.Abs.VId id_ -> prPrec i 0 (concatD [prt 0 id_])
    Jezyk.Abs.VAt id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "at"), prt 0 expr])

instance Print Jezyk.Abs.Arg where
  prt i = \case
    Jezyk.Abs.AId id_ -> prPrec i 0 (concatD [prt 0 id_])
    Jezyk.Abs.ASeq id_ arg -> prPrec i 0 (concatD [prt 0 id_, doc (showString ","), prt 0 arg])

instance Print Jezyk.Abs.Stmt where
  prt i = \case
    Jezyk.Abs.SCall id_ -> prPrec i 0 (concatD [doc (showString "call"), prt 0 id_])
    Jezyk.Abs.SCallA id_ arg -> prPrec i 0 (concatD [doc (showString "call"), prt 0 id_, doc (showString "with"), prt 0 arg])
    Jezyk.Abs.SAssgn var expr -> prPrec i 1 (concatD [doc (showString "set"), prt 0 var, doc (showString "to"), prt 0 expr])
    Jezyk.Abs.SAssgnF var id_ -> prPrec i 1 (concatD [doc (showString "set"), prt 0 var, doc (showString "to"), doc (showString "call"), prt 0 id_])
    Jezyk.Abs.SAssgnFA var id_ arg -> prPrec i 1 (concatD [doc (showString "set"), prt 0 var, doc (showString "to"), doc (showString "call"), prt 0 id_, doc (showString "with"), prt 0 arg])
    Jezyk.Abs.SDel expr id_ -> prPrec i 1 (concatD [doc (showString "del"), prt 0 expr, doc (showString "from"), prt 0 id_])
    Jezyk.Abs.SIfte bexpr stmt1 stmt2 -> prPrec i 2 (concatD [doc (showString "if"), prt 0 bexpr, doc (showString "then"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2, doc (showString "end")])
    Jezyk.Abs.SIfend bexpr stmt -> prPrec i 2 (concatD [doc (showString "if"), prt 0 bexpr, doc (showString "then"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.SWhile bexpr stmt -> prPrec i 2 (concatD [doc (showString "while"), prt 0 bexpr, doc (showString "do"), prt 1 stmt])
    Jezyk.Abs.SFor id_ expr1 expr2 stmt -> prPrec i 2 (concatD [doc (showString "for"), prt 0 id_, doc (showString "from"), prt 0 expr1, doc (showString "to"), prt 0 expr2, doc (showString "do"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.SForKeys id_1 id_2 stmt -> prPrec i 2 (concatD [doc (showString "for"), prt 0 id_1, doc (showString "in"), doc (showString "keys"), prt 0 id_2, doc (showString "do"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.SForVals id_1 id_2 stmt -> prPrec i 2 (concatD [doc (showString "for"), prt 0 id_1, doc (showString "in"), doc (showString "values"), prt 0 id_2, doc (showString "do"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.SForPairs id_1 id_2 id_3 stmt -> prPrec i 2 (concatD [doc (showString "for"), prt 0 id_1, doc (showString ","), prt 0 id_2, doc (showString "in"), prt 0 id_3, doc (showString "do"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.SPrint id_ -> prPrec i 0 (concatD [doc (showString "print"), prt 0 id_])
    Jezyk.Abs.SBlock decl stmt -> prPrec i 0 (concatD [doc (showString "begin"), prt 0 decl, doc (showString ";"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.STry stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "try"), prt 0 stmt1, doc (showString "catch"), prt 0 stmt2, doc (showString "end")])
    Jezyk.Abs.SSeq stmt1 stmt2 -> prPrec i 0 (concatD [prt 1 stmt1, doc (showString ";"), prt 0 stmt2])

instance Print Jezyk.Abs.BExpr where
  prt i = \case
    Jezyk.Abs.BAnd bexpr1 bexpr2 -> prPrec i 0 (concatD [prt 0 bexpr1, doc (showString "&"), prt 1 bexpr2])
    Jezyk.Abs.BOr bexpr1 bexpr2 -> prPrec i 0 (concatD [prt 0 bexpr1, doc (showString "|"), prt 1 bexpr2])
    Jezyk.Abs.BNot bexpr -> prPrec i 1 (concatD [doc (showString "!"), prt 3 bexpr])
    Jezyk.Abs.BEq expr1 expr2 -> prPrec i 2 (concatD [prt 1 expr1, doc (showString "="), prt 1 expr2])
    Jezyk.Abs.BLt expr1 expr2 -> prPrec i 2 (concatD [prt 1 expr1, doc (showString "<"), prt 1 expr2])
    Jezyk.Abs.BLeq expr1 expr2 -> prPrec i 2 (concatD [prt 1 expr1, doc (showString "<="), prt 1 expr2])
    Jezyk.Abs.BGt expr1 expr2 -> prPrec i 2 (concatD [prt 1 expr1, doc (showString ">"), prt 1 expr2])
    Jezyk.Abs.BGeq expr1 expr2 -> prPrec i 2 (concatD [prt 1 expr1, doc (showString ">="), prt 1 expr2])
    Jezyk.Abs.BNeq expr1 expr2 -> prPrec i 2 (concatD [prt 1 expr1, doc (showString "!="), prt 1 expr2])
    Jezyk.Abs.BTrue -> prPrec i 3 (concatD [doc (showString "true")])
    Jezyk.Abs.BFalse -> prPrec i 3 (concatD [doc (showString "false")])
    Jezyk.Abs.BCheck expr id_ -> prPrec i 2 (concatD [doc (showString "check"), prt 0 expr, doc (showString "in"), prt 0 id_])

instance Print Jezyk.Abs.Expr where
  prt i = \case
    Jezyk.Abs.EPlus expr1 expr2 -> prPrec i 1 (concatD [prt 1 expr1, doc (showString "+"), prt 2 expr2])
    Jezyk.Abs.EMinus expr1 expr2 -> prPrec i 1 (concatD [prt 1 expr1, doc (showString "-"), prt 2 expr2])
    Jezyk.Abs.EMul expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, doc (showString "*"), prt 3 expr2])
    Jezyk.Abs.EDiv expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, doc (showString "/"), prt 3 expr2])
    Jezyk.Abs.ENeg expr -> prPrec i 3 (concatD [doc (showString "-"), prt 4 expr])
    Jezyk.Abs.ENum n -> prPrec i 4 (concatD [prt 0 n])
    Jezyk.Abs.EVar id_ -> prPrec i 4 (concatD [prt 0 id_])
    Jezyk.Abs.Etern bexpr expr1 expr2 -> prPrec i 0 (concatD [prt 0 bexpr, doc (showString "?"), prt 1 expr1, doc (showString ":"), prt 1 expr2])

instance Print Jezyk.Abs.Type where
  prt i = \case
    Jezyk.Abs.TBool -> prPrec i 0 (concatD [doc (showString "bool")])
    Jezyk.Abs.TInt -> prPrec i 0 (concatD [doc (showString "int")])

instance Print Jezyk.Abs.CType where
  prt i = \case
    Jezyk.Abs.CTArray n type_ -> prPrec i 0 (concatD [doc (showString "array"), doc (showString "of"), prt 0 n, prt 0 type_])
    Jezyk.Abs.CTDict type_ -> prPrec i 0 (concatD [doc (showString "dict"), doc (showString "of"), prt 0 type_])

instance Print Jezyk.Abs.ADecl where
  prt i = \case
    Jezyk.Abs.ADId id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "of"), prt 0 type_])
    Jezyk.Abs.ADSeq id_ type_ adecl -> prPrec i 0 (concatD [prt 0 id_, doc (showString "of"), prt 0 type_, doc (showString ","), prt 0 adecl])

instance Print Jezyk.Abs.FDecl where
  prt i = \case
    Jezyk.Abs.FDVoid -> prPrec i 0 (concatD [doc (showString "fun"), doc (showString "to"), doc (showString "void")])
    Jezyk.Abs.FDRet id_ type_ -> prPrec i 0 (concatD [doc (showString "fun"), doc (showString "to"), prt 0 id_, doc (showString "of"), prt 0 type_])
    Jezyk.Abs.FDArg adecl -> prPrec i 0 (concatD [doc (showString "fun"), doc (showString "from"), prt 0 adecl, doc (showString "to"), doc (showString "void")])
    Jezyk.Abs.FDFull adecl id_ type_ -> prPrec i 0 (concatD [doc (showString "fun"), doc (showString "from"), prt 0 adecl, doc (showString "to"), prt 0 id_, doc (showString "of"), prt 0 type_])

instance Print Jezyk.Abs.Decl where
  prt i = \case
    Jezyk.Abs.DSimple id_ type_ -> prPrec i 1 (concatD [doc (showString "let"), prt 0 id_, doc (showString "be"), prt 0 type_])
    Jezyk.Abs.DComplex id_ ctype -> prPrec i 1 (concatD [doc (showString "let"), prt 0 id_, doc (showString "be"), prt 0 ctype])
    Jezyk.Abs.DFunction id_ fdecl stmt -> prPrec i 1 (concatD [doc (showString "let"), prt 0 id_, doc (showString "be"), prt 0 fdecl, doc (showString "do"), prt 0 stmt, doc (showString "end")])
    Jezyk.Abs.DSeq decl1 decl2 -> prPrec i 0 (concatD [prt 0 decl1, doc (showString ";"), prt 1 decl2])
